[package]
name = "ar-atlas"
version = "1.3.2"
description = "An AR app"
authors = ["Scriptxne"]
license = ""
repository = "https://github.com/Scriptone/LuaAR"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.4", features = [] }

[dependencies]
chrono = "0.4.39"
serde_json = "1.0"
serde = { version = "1.0.217", features = ["derive"] }
log = "0.4"
tauri = { version = "2.2.0", features = ["devtools"] }
tauri-plugin-log = "2.2.0"
tauri-plugin-fs = "2.2.0"
tauri-plugin-dialog = "2.2.0"
tauri-plugin-shell = "2.2.0"
tauri-plugin-process = "2.2.0"
tauri-plugin-persisted-scope = "2.2.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-updater = "2.3.0"

[profile.release]
opt-level = 3
debug = false
strip = "debuginfo"
lto = true
panic = 'unwind'
incremental = true
