import * as shell from "@tauri-apps/plugin-shell"

const skillRoleColors = new Map<Skill, string>()
skillRoleColors.set("Lua", "#26C620")
skillRoleColors.set("C#", "#26C620")
skillRoleColors.set("C++", "#26C620")
skillRoleColors.set("Python", "#26C620")
skillRoleColors.set("Java", "#26C620")
skillRoleColors.set("PHP", "#26C620")
skillRoleColors.set("JavaScript", "#26C620")
skillRoleColors.set("HTML/CSS", "#26C620")
skillRoleColors.set("Voice Actor", "#A57BF7")
skillRoleColors.set("Video Editor", "#F35167")
skillRoleColors.set("Graphics Artist", "#65B9B2")
skillRoleColors.set("Interface Designer", "#65B9B2")
skillRoleColors.set("Texture Artist", "#65B9B2")
skillRoleColors.set("Music Composer", "#A57BF7")
skillRoleColors.set("3D Modeler", "#27B3EE")
skillRoleColors.set("Animator", "#21BD74")
skillRoleColors.set("Clothing", "#CBCA49")
skillRoleColors.set("Builder", "#80A7FF")
skillRoleColors.set("Terrain Editor", "#BED048")
skillRoleColors.set("Sound Effects", "#A57BF7")
skillRoleColors.set("Visual Effects", "#65B9B2")

const skillToVolvic = new Map<Skill, string>()
skillToVolvic.set("Lua", "Scripter")
skillToVolvic.set("C#", "OffsiteProgrammer")
skillToVolvic.set("C++", "OffsiteProgrammer")
skillToVolvic.set("Python", "OffsiteProgrammer")
skillToVolvic.set("Java", "OffsiteProgrammer")
skillToVolvic.set("PHP", "OffsiteProgrammer")
skillToVolvic.set("JavaScript", "OffsiteProgrammer")
skillToVolvic.set("HTML/CSS", "OffsiteProgrammer")
skillToVolvic.set("Graphics Artist", "Graphics")
skillToVolvic.set("Texture Artist", "Graphics")
skillToVolvic.set("Clothing", "Clothing")
skillToVolvic.set("Terrain Editor", "Builder")
skillToVolvic.set("Builder", "Builder")
skillToVolvic.set("3D Modeler", "Modeller")
skillToVolvic.set("Visual Effects", "Modeller")
skillToVolvic.set("Sound Effects", "SoundEffects")
skillToVolvic.set("Music Composer", "SoundEffects")
skillToVolvic.set("Animator", "Animator")
skillToVolvic.set("Interface Designer", "UserInterface")
skillToVolvic.set("Voice Actor", "VoiceActors")
skillToVolvic.set("Video Editor", "VideoEditor")
const openInBrowser = shell.open

export { openInBrowser, skillRoleColors, skillToVolvic }
